import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Link, useRouterState } from '@tanstack/react-router';
import { ArrowUpRight, ArrowDown, ArrowRight, ArrowLeft, Menu as MenuIcon, X, Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { images, nav, menu, gallery } from './data';

export function Reveal({children, className = ''}: {children: ReactNode; className?: string}) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const element = ref.current;
    if (!element) return;
    const observer = new IntersectionObserver(([entry]) => { if (entry?.isIntersecting) { element.classList.add('is-visible'); observer.disconnect(); } }, {threshold: .12});
    observer.observe(element);
    return () => observer.disconnect();
  }, []);
  return <div ref={ref} className={`reveal ${className}`}>{children}</div>;
}
export function Brand() { return <span className="brand">caffein<span className="brand-dot">.</span></span>; }
export function Header() {
  const [open, setOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const pathname = useRouterState({select: state => state.location.pathname});
  const toggleRef = useRef<HTMLButtonElement>(null);
  const mobileRef = useRef<HTMLElement>(null);
  useEffect(() => { const change = () => setScrolled(window.scrollY > 30); change(); window.addEventListener('scroll', change, {passive:true}); return () => window.removeEventListener('scroll', change); }, []);
  useEffect(() => { setOpen(false); }, [pathname]);
  useEffect(() => {
    if (!open) return;
    const previous = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    mobileRef.current?.querySelector<HTMLAnchorElement>('a')?.focus();
    const key = (event: KeyboardEvent) => {
      if (event.key === 'Escape') { setOpen(false); toggleRef.current?.focus(); }
      if (event.key === 'Tab') {
        const links = mobileRef.current?.querySelectorAll<HTMLAnchorElement>('a');
        const first = links?.[0]; const last = links?.[links.length - 1];
        if (event.shiftKey && document.activeElement === first) { event.preventDefault(); toggleRef.current?.focus(); }
        else if (!event.shiftKey && document.activeElement === last) {event.preventDefault(); toggleRef.current?.focus();}
        else if (document.activeElement === toggleRef.current) {event.preventDefault(); (event.shiftKey ? last : first)?.focus();}
      }
    };
    document.addEventListener('keydown', key);
    return () => {document.body.style.overflow = previous; document.removeEventListener('keydown',key);};
  }, [open]);
  return <><a href="#main" className="skip-link">Skip to content</a><header className={`site-header ${scrolled ? 'scrolled' : ''}`}>
    <Link to="/" aria-label="Caffein home"><Brand /></Link>
    <nav aria-label="Main navigation" className="desktop-nav">{nav.map(([label,to]) => <Link key={to} to={to} className={`nav-link ${pathname === to ? 'active' : ''}`}>{label}</Link>)}</nav>
    <Button asChild className="visit-button"><Link to="/contact">Visit Us <ArrowUpRight /></Link></Button>
    <Button ref={toggleRef} variant="ghost" size="icon" className="mobile-toggle" aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open} aria-controls="mobile-nav" onClick={() => setOpen(!open)}>{open ? <X/> : <MenuIcon/>}</Button>
  </header><nav ref={mobileRef} id="mobile-nav" aria-label="Mobile navigation" className={`mobile-nav ${open ? 'open' : ''}`} inert={!open}>{nav.map(([label,to], index) => <Link key={to} to={to}><span>0{index + 1}</span>{label}<ArrowUpRight /></Link>)}<p>Good coffee. A little slower.</p></nav></>;
}
export function TextLink({to, children}: {to: '/about' | '/menu' | '/experience' | '/gallery' | '/contact'; children: ReactNode}) {return <Link className="text-link" to={to}>{children}<ArrowUpRight size={18}/></Link>;}
export function Photo({src, alt, className = ''}: {src:string;alt:string;className?:string}) {return <div className={`photo ${className}`}><img src={src} alt={alt} loading="lazy" width={1536} height={1280}/></div>;}
export function Hero() {
  return <section className="hero" aria-labelledby="hero-title"><img className="hero-image" src={images.interior} alt="A sunlit Caffein café with walnut tables and a welcoming espresso bar" width={1920} height={1280} fetchPriority="high"/><div className="hero-shade"/><div className="hero-content"><p className="eyebrow hero-eyebrow">THE ART OF EVERYDAY COFFEE</p><h1 id="hero-title"><span>Coffee, Crafted</span><span>With <em>Character.</em></span></h1><p className="hero-description">Thoughtfully sourced. Carefully crafted.<br/>A little pause, made beautifully.</p><Button asChild className="hero-button"><Link to="/menu">Discover our menu <ArrowUpRight/></Link></Button><Link className="hero-secondary" to="/experience">Take a moment with us</Link></div><div className="hero-bottom"><span>GOOD COFFEE. GOOD COMPANY.</span><a href="#story" aria-label="Explore our story" className="scroll-cue"><span>SCROLL TO DISCOVER</span><ArrowDown size={17}/></a><span>YOUR DAILY RITUAL, REIMAGINED.</span></div></section>;
}
export function RitualBand() { return <div className="ritual-band"><span>Specialty coffee</span><i>✳</i><span>Slow mornings</span><i>✳</i><span>Freshly baked</span><i>✳</i><span>Meaningful moments</span><i>✳</i></div>; }
export function Story({full = false}: {full?: boolean}) {
  return <section id="story" className="section story-section"><Reveal className="story-grid"><div><p className="eyebrow">01 — OUR STORY</p><h2>More than coffee.<br/>A feeling of <em>belonging.</em></h2></div><div className="story-copy"><p>We believe the best things in life aren’t rushed. A perfectly poured coffee. A warm conversation. A quiet corner that feels like your own.</p><p>Caffein is our way of bringing those little things together. Thoughtful coffee, honest food, and a space to simply be.</p><TextLink to="/about">A little about us</TextLink></div><span className="decorative-number" aria-hidden="true">01</span></Reveal>{full && <Reveal className="extended-story"><Photo src={images.coffee} alt="Carefully crafted coffee in handmade ceramic cups"/><div><p className="eyebrow">A SIMPLE IDEA, MADE WITH CARE</p><h2>For the love<br/>of the <em>little things.</em></h2><p>Our story starts with a simple idea: the everyday deserves a little more care. So we created a place where every cup has a story, every ingredient has a purpose, and there is always room at the table.</p><p>From the first morning grind to the last conversation of the afternoon, it’s the people and the small rituals that make Caffein what it is.</p></div></Reveal>}</section>;
}
export function Experience({full=false}: {full?:boolean}) {return <section className="experience-section"><Reveal className="section-heading"><p className="eyebrow">02 — THE CAFFEIN EXPERIENCE</p><h2>Stay a little <em>longer.</em></h2><p>Find your corner. Order your favourite. Let the world wait.</p></Reveal><Reveal className="experience-visual"><Photo src={images.interior} alt="Our warm café interior, made for slow mornings"/><div className="experience-note"><span className="eyebrow">A SPACE TO SIMPLY BE</span><h3>Your pause.<br/>Your place.</h3><p>Sunlit corners, familiar faces, and the comforting aroma of something good.</p><TextLink to="/contact">Find your way here</TextLink></div><span className="image-caption">EVERY DETAIL, A LITTLE MORE INTENTIONAL.</span></Reveal>{full && <div className="section"><Reveal className="extended-story"><div><p className="eyebrow">YOUR TABLE IS WAITING</p><h2>Come for a cup.<br/>Stay for the <em>moment.</em></h2><p>A morning with your favourite book. An afternoon catching up with an old friend. A quiet hour just for you. Whatever brings you in, make yourself at home.</p><TextLink to="/menu">Find your new favourite</TextLink></div><Photo src={images.exterior} alt="Café tables on a peaceful terrace"/></Reveal></div>}</section>;}
export function MenuSection({full=false}:{full?:boolean}) {
  const [category, setCategory] = useState<keyof typeof menu>('Coffee');
  const keys = Object.keys(menu) as (keyof typeof menu)[];
  return <section className="section menu-section"><Reveal className="menu-heading"><div><p className="eyebrow">03 — MADE TO BE SAVOURED</p><h2>A few of our<br/><em>favourite things.</em></h2></div><p>Good ingredients. No shortcuts.<br/>A menu made for every mood.</p></Reveal><Reveal className="menu-layout"><div className="menu-list"><div className="menu-tabs" role="tablist" aria-label="Menu category">{keys.map(key => <Button key={key} id={`tab-${key.replaceAll(' ','-')}`} role="tab" aria-selected={category === key} aria-controls="menu-panel" variant="ghost" className={category === key ? 'selected' : ''} onClick={() => setCategory(key)} onKeyDown={event => { if (event.key === 'ArrowRight' || event.key === 'ArrowLeft') {event.preventDefault(); const next = keys[(keys.indexOf(category) + (event.key === 'ArrowRight' ? 1 : keys.length - 1)) % keys.length]; if (!next) return; setCategory(next); document.getElementById(`tab-${next.replaceAll(' ','-')}`)?.focus();} }}>{key}</Button>)}</div><div id="menu-panel" role="tabpanel" aria-labelledby={`tab-${category.replaceAll(' ','-')}`} key={category} className="menu-panel">{menu[category].map(([name,description,price],i) => <div key={name} className="menu-row"><span className="item-number">0{i+1}</span><div><h3>{name}</h3><p>{description}</p></div><span className="menu-price"><span className="currency-symbol">₹</span>{price}</span></div>)}</div><div className="menu-footnote"><span>Oat milk & decaf always welcome.</span>{!full && <TextLink to="/menu">Explore the menu</TextLink>}</div></div><Photo src={category === 'Coffee' || category === 'Signature Drinks' ? images.coffee : images.pastries} alt={category === 'Coffee' || category === 'Signature Drinks' ? 'Our signature coffee, beautifully poured' : 'Fresh pastries and handmade cake'} className="menu-photo"/></Reveal>{full && <p className="sample-note">Sample menu & prices. Seasonal favourites may vary.</p>}</section>;
}
export function GallerySection({full=false}:{full?:boolean}) {
  const [selected,setSelected] = useState<number|null>(null);
  const selectedImage = selected === null ? undefined : gallery[selected];
  const next = (direction:number) => setSelected(current => current === null ? 0 : (current + direction + gallery.length) % gallery.length);
  return <section className="section gallery-section"><Reveal className="gallery-heading"><div><p className="eyebrow">04 — THROUGH OUR LENS</p><h2>Life, in little <em>moments.</em></h2></div>{!full && <TextLink to="/gallery">A closer look</TextLink>}</Reveal><div className="gallery-grid">{gallery.map((image,index) => <Reveal key={index} className={`gallery-item ${image.className}`}><Button variant="ghost" className="gallery-button" onClick={() => setSelected(index)} aria-label={`View ${image.alt.toLowerCase()}`}><img src={image.src} alt={image.alt} width={1280} height={1536} loading="lazy"/><span className="gallery-hover"><span>CAFFEIN, IN FOCUS</span><Plus size={24}/></span></Button></Reveal>)}</div><Dialog open={selected !== null} onOpenChange={open => {if (!open) setSelected(null);}}><DialogContent className="gallery-dialog" onKeyDown={event => {if(event.key === 'ArrowRight')next(1); if(event.key === 'ArrowLeft')next(-1);}}><DialogTitle className="sr-only">{selectedImage?.alt ?? 'Caffein gallery'}</DialogTitle><DialogDescription className="sr-only">Photographs of coffee, food and the café.</DialogDescription>{selectedImage && <><img src={selectedImage.src} alt={selectedImage.alt}/><div className="lightbox-bottom"><Button variant="ghost" size="icon" aria-label="Previous photo" onClick={() => next(-1)}><ArrowLeft/></Button><span>{selectedImage.alt}<small>{(selected ?? 0) + 1} / {gallery.length}</small></span><Button variant="ghost" size="icon" aria-label="Next photo" onClick={() => next(1)}><ArrowRight/></Button></div></>}</DialogContent></Dialog></section>;
}
export function Values() {return <section className="values-section section"><Reveal><p className="eyebrow">THE LITTLE THINGS THAT MATTER</p><h2>Good by <em>nature.</em></h2></Reveal><div className="values-grid">{[['01','Crafted Daily','From the first espresso to the last pastry, fresh is our favourite way to start.'],['02','Premium Ingredients','Thoughtfully sourced beans. Honest ingredients. Nothing we don’t believe in.'],['03','Relaxed Atmosphere','A welcoming space to slow down, settle in, and feel completely at home.'],['04','Made for Moments','The everyday catch-ups and quiet rituals that become your favourite memories.']].map(([num,title,copy]) => <Reveal className="value" key={num}><span>{num}</span><h3>{title}</h3><p>{copy}</p></Reveal>)}</div></section>;}
const quotes = [['“Some places serve coffee. Caffein makes you feel at home. My favourite little ritual in the city.”','Sophie M.','A familiar face, since day one'],['“Beautiful coffee, a warm welcome, and absolutely no reason to hurry. Exactly what a morning should be.”','James R.','The flat white enthusiast'],['“The kind of place you find by chance, and come back to on purpose. That pistachio croissant is everything.”','Emma L.','A little sweetness, every weekend']];
export function Testimonials() {
  const [index,setIndex] = useState(0);
  return <section className="quote-section section"><Reveal><p className="eyebrow">KIND WORDS, WARM HEARTS</p><div className="quote-mark" aria-hidden="true">“</div><div className="quote-content" key={index}><blockquote>{quotes[index]?.[0]}</blockquote><p className="quote-name">{quotes[index]?.[1]}</p><p className="quote-detail">{quotes[index]?.[2]}</p></div><div className="quote-controls"><Button variant="ghost" size="icon" aria-label="Previous testimonial" onClick={() => setIndex((index+2)%3)}><ArrowLeft/></Button><span>0{index+1} <span className="text-muted-foreground">/ 03</span></span><Button variant="ghost" size="icon" aria-label="Next testimonial" onClick={() => setIndex((index+1)%3)}><ArrowRight/></Button></div></Reveal></section>;
}
export function Visit({full=false}:{full?:boolean}) {return <section className="section visit-section"><Reveal className="visit-grid"><div><p className="eyebrow">05 — YOUR TABLE IS WAITING</p><h2>A little closer<br/>to your next <em>coffee.</em></h2><p className="visit-intro">Walk in, slow down, make yourself at home.<br/>We’ll put the coffee on.</p><div className="visit-details"><div><h3>FIND US</h3><p>24 Coffee Lane<br/>Your neighbourhood, your city</p></div><div><h3>COME BY</h3><p>Monday – Friday <span>7:30 – 18:00</span><br/>Saturday – Sunday <span>8:30 – 18:00</span></p></div><div><h3>SAY HELLO</h3><p>hello@caffein.example<br/>+00 123 456 789</p></div></div><Button asChild className="dark-button"><a href="https://www.google.com/maps/search/cafe+near+me/" target="_blank" rel="noopener noreferrer">Get directions <ArrowUpRight/></a></Button>{full && <p className="sample-note">Illustrative address, hours and contact details.</p>}</div><Photo src={images.exterior} alt="A welcoming café entrance and sunlit outdoor tables"/></Reveal></section>;}
export function FinalCTA() {return <section className="final-cta"><img src={images.interior} width={1920} height={1280} alt="Warm light across the café, ready for your next visit" loading="lazy"/><div className="final-shade"/><Reveal><p className="eyebrow">THERE’S ALWAYS TIME FOR GOOD COFFEE</p><h2>Your next coffee moment<br/>starts <em>here.</em></h2><Button asChild className="hero-button"><Link to="/contact">Visit Us <ArrowUpRight/></Link></Button></Reveal></section>;}
export function Footer() {return <footer className="section footer"><div className="footer-top"><div><Link to="/" aria-label="Caffein home"><Brand/></Link><p>Good coffee. Honest food.<br/>A place to pause.</p></div><nav aria-label="Footer navigation">{nav.slice(1).map(([name,to]) => <Link key={to} to={to}>{name}</Link>)}<Link to="/admin">Admin</Link></nav><div className="footer-contact"><p>LET’S STAY A LITTLE CLOSER</p><span>hello@caffein.example</span><div><a href="https://www.instagram.com/" target="_blank" rel="noopener noreferrer">Instagram <ArrowUpRight size={14}/></a><a href="https://www.pinterest.com/" target="_blank" rel="noopener noreferrer">Pinterest <ArrowUpRight size={14}/></a></div></div></div><div className="footer-bottom"><span>© 2026 Caffein. All rights reserved.</span><span>CRAFTED WITH CARE. SAVOURED SLOWLY.</span><a href="#main">Back to top ↑</a></div></footer>;}
export function PageTitle({label,title,italic,description}:{label:string;title:string;italic:string;description:string}) {return <section className="page-title section"><p className="eyebrow">{label}</p><h1>{title} <em>{italic}</em></h1><p>{description}</p></section>;}
export function SiteLayout({children}:{children:ReactNode}) {return <><Header/><main id="main">{children}</main><Footer/></>;}
